Repository MetOffice/CSET, pull requests merged in 2023-11, with the labels that each got.

#201 Use hash of updated lock files in branch name
  .github/workflows/conda-lock.yml
Labels: bug, small

#190 Add note on updating a cloned repository
  docs/source/contributing/getting-started.rst
Labels: documentation, good first issue, small

#200 Skip build-docs on push to main
  .github/workflows/documentation.yml
  .github/workflows/pr_ci.yml
Labels: small, cleanup

#202 Python 3.12 support
  .github/workflows/conda-lock.yml
  .github/workflows/documentation.yml
  .github/workflows/pr_ci.yml
  pyproject.toml
  requirements/locks/py312-lock-linux-64.txt
Labels: enhancement

#229 Fix globbing for lock file hashing
  .github/workflows/conda-lock.yml
Labels: bug

#245 Use static branch name while updating lock files
  .github/workflows/conda-lock.yml
Labels: bug

#218 Swap out flake8 for Ruff
  .gitignore
  .pre-commit-config.yaml
  docs/source/conf.py
  pyproject.toml
  setup.cfg
  src/CSET/__init__.py
  src/CSET/__main__.py
  src/CSET/_common.py
  src/CSET/graph.py
  src/CSET/operators/__init__.py
  src/CSET/operators/collapse.py
  src/CSET/operators/constraints.py
  src/CSET/operators/filters.py
  src/CSET/operators/misc.py
  src/CSET/operators/plot.py
  src/CSET/operators/read.py
  src/CSET/operators/write.py
  src/CSET/recipes/__init__.py
  tests/operators/test_collapse.py
  tests/operators/test_constraints.py
  tests/operators/test_filters.py
  tests/operators/test_misc.py
  tests/operators/test_plots.py
  tests/operators/test_read.py
  tests/test_cli.py
  tests/test_common.py
  tests/test_graph.py
  tests/test_recipes.py
  tests/test_run_recipes.py
Labels: cleanup

#258 Fix filter operator for filtering cube
  src/CSET/operators/filters.py
  tests/operators/test_filters.py
Labels: bug, small

#273 Fix pre-commit mangling test data
  .pre-commit-config.yaml
Labels: bug, small

#209 Improve tutorials
  docs/source/contributing/getting-started.rst
  docs/source/getting-started/create-first-recipe.rst
  docs/source/getting-started/index.rst
  docs/source/getting-started/installation.rst
  docs/source/getting-started/recipe-graph-details.svg
  docs/source/getting-started/recipe-graph.svg
  docs/source/getting-started/run-recipe.rst
  docs/source/getting-started/visualise-recipe.rst
  docs/source/reference/cli.rst
  src/CSET/__init__.py
  src/CSET/recipes/mean_surface_air_temperature_spatial_plot.yaml
  tests/test_cli.py
Labels: documentation

#274 Plot generation improvements
  docs/source/reference/cli.rst
  docs/source/reference/recipe-format.rst
  pyproject.toml
  requirements/environment.yml
  requirements/locks/py310-lock-linux-64.txt
  requirements/locks/py311-lock-linux-64.txt
  requirements/locks/py312-lock-linux-64.txt
  requirements/locks/py39-lock-linux-64.txt
  src/CSET/__init__.py
  src/CSET/_common.py
  src/CSET/operators/__init__.py
  src/CSET/operators/constraints.py
  src/CSET/operators/plot.py
  src/CSET/operators/write.py
  src/CSET/recipes/aggregate_precipitation.yaml
  src/CSET/recipes/ensemble_3_hour_air_temp.yaml
  src/CSET/recipes/extract_instant_air_temp.yaml
  src/CSET/recipes/initial_time-step_surface_air_temperature_ensemble_postage_stamp_plot.yaml
  tests/operators/test_plots.py
  tests/test_cli.py
  tests/test_common.py
  tests/test_data/ensemble_air_temp.yaml
  tests/test_data/plot_instant_air_temp.yaml
  tests/test_data/plot_instant_air_temp_collapse.yaml
  tests/test_recipes.py
  tests/test_run_recipes.py
Labels: enhancement

#278 Bump version to 0.5.0
  pyproject.toml
Labels: small, cleanup

#282 Improve contour plot
  docs/source/reference/operators.rst
  src/CSET/operators/collapse.py
  src/CSET/operators/plot.py
Labels: enhancement

#283 Bump version to 0.6.0
  pyproject.toml
Labels: cleanup
