Repository MetOffice/CSET, pull requests merged in 2024-12, with the labels that each got.

#951 Use non-interactive backend for plotting
  src/CSET/operators/plot.py
Labels: bug, small

#955 Update to WEB_ADDR documentation.
  cset-workflow/meta/rose-meta.conf
Labels: bug, documentation, small

#884 Add nicer error messages for unhandled exceptions
  src/CSET/__init__.py
Labels: cleanup

#963 Target lockfile update PR to source branch
  .github/workflows/conda-lock.yml
Labels: github_actions

#463 Use regular install for CI tests
  .github/workflows/pull_request_checks.yml
Labels: small, cleanup

#967 Add mask operators
  src/CSET/operators/filters.py
  src/CSET/recipes/example_combined_mask_addition.yaml
  src/CSET/recipes/example_combined_mask_multiplication.yaml
  src/CSET/recipes/example_simple_mask.yaml
  src/CSET/recipes/example_spatial_plot_of_mask.yaml
  tests/operators/test_filters.py
Labels: enhancement

#979 Adds spatial perturbation operator
  docs/source/reference/operators.rst
  src/CSET/operators/__init__.py
  src/CSET/operators/mesoscale.py
  src/CSET/recipes/Example_Gaussian_Spatial_Perturbation.yaml
  src/CSET/recipes/Example_Uniform_Spatial_Perturbation.yaml
  tests/operators/test_mesoscale.py
Labels: enhancement

#983 New callbacks to standardise some dim names
  src/CSET/operators/_utils.py
  src/CSET/operators/read.py
  tests/operators/test_read.py
  tests/operators/test_utils.py
Labels: bug, enhancement

#1006 Fix no title in surface histogram plots
  src/CSET/recipes/generic_surface_histogram_series.yaml
Labels: bug, small

#1003 Updates generate_levels_constraint documentation for ensemble functionality
  src/CSET/operators/constraints.py
Labels: documentation, small
