Repository MetOffice/CSET, pull requests merged in 2024-04, with the labels that each got.

#470 Improve workflow documentation
  README.md
  cset-workflow/flow.cylc
  cset-workflow/meta/rose-meta.conf
  docs/source/index.rst
  docs/source/usage/rose-edit.png
  docs/source/usage/workflow-installation.rst
Labels: documentation

#405 Basic regrid operator
  docs/source/reference/operators.rst
  src/CSET/operators/regrid.py
  tests/operators/test_regrid.py
  tests/test_data/regrid/out_rectilinearGeogCS_0p5deg.nc
  tests/test_data/regrid/regrid_rectilinearGeogCS.nc
Labels: enhancement

#387 Include file looping
  cset-workflow/app/fetch_fcst/bin/fetch-data-filesystem.py
  cset-workflow/app/fetch_fcst/bin/fetch-data-filesystem.sh
  cset-workflow/app/fetch_fcst/opt/rose-app-filesystem.conf
  cset-workflow/app/fetch_fcst/opt/rose-app-mass.conf
  cset-workflow/app/housekeeping/bin/housekeep.sh
  cset-workflow/app/install_website_skeleton/bin/install-website.sh
  cset-workflow/app/install_website_skeleton/file/html/plots/index.json
  cset-workflow/app/install_website_skeleton/file/html/static/script.js
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  cset-workflow/flow.cylc
  cset-workflow/includes/plot_spatial_surface_model_field.cylc
  cset-workflow/meta/rose-meta.conf
  src/CSET/_common.py
  src/CSET/operators/__init__.py
  src/CSET/operators/constraints.py
  src/CSET/operators/filters.py
  src/CSET/operators/plot.py
  src/CSET/recipes/generic_surface_spatial_plot_sequence.yaml
  tests/operators/test_constraints.py
  tests/operators/test_filters.py
  tests/test_common.py
Labels: enhancement

#435 Link from getting started to contribution guide
  docs/source/getting-started/index.rst
  docs/source/index.rst
Labels: documentation, small

#449 Simplify documentation workflow
  .github/workflows/documentation.yml
Labels: cleanup

#434 Change contribution documentation section title
  docs/source/contributing/index.rst
Labels: documentation, small

#441 Looping model level
  cset-workflow/includes/plot_spatial_plevel_model_field.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/constraints.py
  src/CSET/recipes/generic_plevel_spatial_plot_sequence.yaml
  tests/operators/test_constraints.py
Labels: enhancement

#491 Non-UMified LFRic handling
  src/CSET/_common.py
  src/CSET/operators/filters.py
  src/CSET/operators/misc.py
  src/CSET/operators/read.py
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  tests/operators/test_read.py
  tests/test_common.py
Labels: enhancement

#483 Include recipe title in plots title
  src/CSET/operators/plot.py
Labels: enhancement, small

#482 Close figures after saving, and refactor plotting code
  src/CSET/operators/plot.py
Labels: bug

#462 Add LFRic specific recipes
  cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  cset-workflow/meta/rose-meta.conf
  src/CSET/_common.py
  src/CSET/operators/filters.py
  src/CSET/operators/misc.py
  src/CSET/operators/read.py
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  tests/operators/test_misc.py
  tests/operators/test_read.py
  tests/test_common.py
Labels: enhancement

#444 Add explicit deprecation and python support policies
  docs/source/contributing/releases.rst
Labels: documentation

#442 Add feedback links to CSET front page
  cset-workflow/app/install_website_skeleton/file/html/index.html
Labels: enhancement, small

#452 Added generic arithmetic operators
  src/CSET/operators/misc.py
  tests/operators/test_misc.py
Labels: enhancement, full_review

#484 Rename steps and post steps to parallel and collate
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  cset-workflow/flow.cylc
  cset-workflow/includes/deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/domain_mean_time_series_stash.cylc
  cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  cset-workflow/includes/plot_spatial_plevel_model_field.cylc
  cset-workflow/includes/plot_spatial_stash_field.cylc
  cset-workflow/includes/plot_spatial_surface_model_field.cylc
  docs/source/getting-started/create-first-recipe.rst
  docs/source/reference/cli.rst
  docs/source/reference/recipe-format.rst
  src/CSET/__init__.py
  src/CSET/_common.py
  src/CSET/graph.py
  src/CSET/operators/__init__.py
  src/CSET/operators/read.py
  src/CSET/recipes/CAPE_ratio_plot.yaml
  src/CSET/recipes/aggregate_precipitation.yaml
  src/CSET/recipes/extract_instant_air_temp.yaml
  src/CSET/recipes/generic_plevel_spatial_plot_sequence.yaml
  src/CSET/recipes/generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/generic_surface_spatial_plot_sequence.yaml
  src/CSET/recipes/initial_time-step_surface_air_temperature_ensemble_postage_stamp_plot.yaml
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  src/CSET/recipes/mean_surface_air_temperature_spatial_plot.yaml
  src/CSET/recipes/meaned_model_level_air_temperature_spatial_plot.yaml
  src/CSET/recipes/stash_surface_domain_mean_time_series.yaml
  src/CSET/recipes/stash_surface_spatial_plot_sequence.yaml
  src/CSET/recipes/surface_air_temperature_spatial_plot_time_sequence.yaml
  tests/test_cli.py
  tests/test_common.py
  tests/test_data/ensemble_air_temp.yaml
  tests/test_data/noop_recipe.yaml
  tests/test_data/plot_instant_air_temp.yaml
  tests/test_data/plot_instant_air_temp_collapse.yaml
  tests/test_graph.py
  tests/test_run_recipes.py
Labels: documentation, cleanup

#499 Document category recipe key
  docs/source/reference/recipe-format.rst
Labels: documentation, small

#468 Add changelog file
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation, cleanup

#465 Add issue and pull request templates, and detailed contribution checklist
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/pull_request_template.md
  docs/source/changelog.rst
  docs/source/contributing/failing_pr_check.png
  docs/source/contributing/index.rst
  docs/source/contributing/open_pr_symbol.png
  docs/source/contributing/testing.rst
Labels: enhancement, cleanup

#508 Update rose-suite.conf.example so its reflects a modern config
  cset-workflow/rose-suite.conf.example
  docs/source/changelog.rst
Labels: enhancement

#506 Fix spelling in github issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, small

#514 Fix new ruff lint
  src/CSET/operators/plot.py
Labels: bug, small

#541 Update common-errors.rst
  docs/source/changelog.rst
  docs/source/usage/common-errors.rst
Labels: documentation

#556 Add sphinx linkcheck
  .github/workflows/documentation.yml
  .github/workflows/pull_request_checks.yml
  docs/source/changelog.rst
  docs/source/conf.py
  docs/source/contributing/getting-started.rst
  docs/source/contributing/git.rst
Labels: documentation, enhancement

#569 Test and fix `CSET_ADDOPTS` with lists
  docs/source/changelog.rst
  src/CSET/__init__.py
  tests/test_cli.py
  tests/test_data/addopts_test_recipe.yaml
Labels: bug
