Repository MetOffice/CSET, pull requests merged in 2024-07, with the labels that each got.

#717 Fix SET_SUBAREA being required to run some LFRIC recipes
  cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  src/CSET/operators/constraints.py
  src/CSET/recipes/generic_plevel_spatial_plot_sequence.yaml
  src/CSET/recipes/lfric_generic_domain_mean_vertical_profile_series.yaml
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
Labels: bug

#710 Remove deprecated postage stamp contour plot operator
  src/CSET/operators/plot.py
  src/CSET/recipes/inflow_layer_properties_plot.yaml
  tests/operators/test_plots.py
  tests/test_data/ensemble_air_temp.yaml
Labels: cleanup

#711 Remove unneeded fallback code for old recipe step keys
  src/CSET/_common.py
  src/CSET/operators/__init__.py
  tests/test_common.py
Labels: cleanup

#712 Test vertical plotting with a filename specified
  tests/operators/test_plots.py
Labels: small, cleanup

#713 Test running recipes with no collate steps and running with a specified style file
  tests/test_run_recipes.py
Labels: cleanup

#714 Test handling of masked arrays in convection operators, and load convection test files with fixtures
  tests/operators/test_convection.py
  tests/test_data/convection/Orography2D.nc
Labels: cleanup

#716 Ignore cartopy DownloadWarning in pytest
  pyproject.toml
Labels: small, cleanup

#722 Remove unneeded rose edit setting
  cset-workflow/meta/rose-meta.conf
Labels: small, cleanup

#715 Test higher dimentional orography handling in convection operators
  tests/operators/test_convection.py
  tests/test_data/convection/Orography3D.nc
  tests/test_data/convection/Orography3D_ens.nc
  tests/test_data/convection/Orography4D.nc
Labels: cleanup

#723 Support STASH codes in generate_var_constraint
  src/CSET/operators/constraints.py
  tests/operators/test_constraints.py
Labels: enhancement

#531 Add cross-section transect functionality
  cset-workflow/includes/transect.cylc
  cset-workflow/meta/rose-meta.conf
  docs/source/reference/operators.rst
  src/CSET/_common.py
  src/CSET/operators/__init__.py
  src/CSET/operators/_utils.py
  src/CSET/operators/plot.py
  src/CSET/operators/transect.py
  src/CSET/recipes/transect.yaml
  tests/operators/test_transect.py
  tests/operators/test_utils.py
  tests/test_data/transect_out_umml.nc
  tests/test_data/transect_out_umpl.nc
  tests/test_data/transect_test_umml.nc
  tests/test_data/transect_test_umpl.nc
Labels: enhancement, full_review

#697 Extend UM vertical plotting to model level
  cset-workflow/includes/deterministic_domain_mean_vertical_profile_modellevel_series.cylc
  cset-workflow/meta/rose-meta.conf
  src/CSET/recipes/generic_domain_mean_vertical_profile_modellevel_series.yaml
Labels: enhancement

#699 UM spatial plot on model levels
  cset-workflow/includes/plot_spatial_mlevel_model_field.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/recipes/generic_mlevel_spatial_plot_sequence.yaml
Labels: enhancement

#695 Enable spatial fields on full and half levels
  cset-workflow/meta/rose-meta.conf
  src/CSET/recipes/lfric_generic_mlevel_spatial_plot_sequence.yaml
Labels: enhancement

#731 Fix bug in transect operator
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/transect.py
Labels: bug

#729 Unquote double quoted shell values
  cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  src/CSET/__init__.py
  src/CSET/_common.py
  src/CSET/operators/constraints.py
  tests/test_common.py
Labels: bug

#733 Remove invalid rose meta trigger for removed variable
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
Labels: bug, small

#735 Add _utils operators to internal function documentation
  docs/source/reference/internal.rst
Labels: documentation, small

#749 Don't check documentation hyperlinks in commit CI
  .github/workflows/pull_request_checks.yml
  .github/workflows/weekly-checks.yml
Labels: cleanup

#594 Generate Histograms for 2D field
  cset-workflow/includes/domain_histogram_series.cylc
  cset-workflow/includes/lfric_domain_histogram_series.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  docs/source/changelog.rst
  src/CSET/operators/plot.py
  src/CSET/recipes/generic_domain_mean_vertical_profile_series.yaml
  src/CSET/recipes/generic_histogram_series.yaml
  src/CSET/recipes/generic_mlevel_spatial_plot_sequence.yaml
  src/CSET/recipes/lfric_generic_histogram_series.yaml
  tests/conftest.py
  tests/operators/test_plots.py
Labels: science, full_review

#641 Tidy up documentation around recipes and cset bake command, introducing examples
  docs/source/reference/cli.rst
  docs/source/reference/recipe-format.rst
Labels: documentation

#738 Create operator to combine Cubes/CubeList into single CubeList
  src/CSET/operators/misc.py
  tests/conftest.py
  tests/operators/test_misc.py
  tests/operators/test_plots.py
  tests/operators/test_utils.py
Labels: enhancement

#753 Update copyright attribution per legal advice
  README.md
  cset-workflow/extra-meta/alphabetical_dict.py
  docs/source/conf.py
  docs/source/index.rst
  src/CSET/__init__.py
  src/CSET/__main__.py
  src/CSET/_common.py
  src/CSET/graph.py
  src/CSET/operators/__init__.py
  src/CSET/operators/_utils.py
  src/CSET/operators/aggregate.py
  src/CSET/operators/collapse.py
  src/CSET/operators/constraints.py
  src/CSET/operators/convection.py
  src/CSET/operators/filters.py
  src/CSET/operators/misc.py
  src/CSET/operators/plot.py
  src/CSET/operators/read.py
  src/CSET/operators/regrid.py
  src/CSET/operators/transect.py
  src/CSET/operators/write.py
  src/CSET/recipes/__init__.py
  tests/conftest.py
  tests/operators/test_aggregate.py
  tests/operators/test_collapse.py
  tests/operators/test_constraints.py
  tests/operators/test_convection.py
  tests/operators/test_filters.py
  tests/operators/test_misc.py
  tests/operators/test_plots.py
  tests/operators/test_read.py
  tests/operators/test_regrid.py
  tests/operators/test_transect.py
  tests/operators/test_utils.py
  tests/operators/test_write.py
  tests/test_cli.py
  tests/test_common.py
  tests/test_graph.py
  tests/test_recipes.py
  tests/test_run_recipes.py
Labels: documentation, cleanup

#734 Regrid to take CubeList and Cubes
  src/CSET/operators/regrid.py
  tests/operators/test_regrid.py
Labels: enhancement

#728 Enhance level filter operator to return all vertical levels
  cset-workflow/includes/transect.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/constraints.py
  src/CSET/recipes/transect.yaml
  tests/operators/test_constraints.py
  tests/operators/test_filters.py
  tests/test_data/vertlevtestdata.nc
Labels: enhancement

#759 Mass retrieval fix
  cset-workflow/app/fetch_fcst/opt/rose-app-mass.conf
Labels: bug, small

#472 Copy source files from any named folder when installing locally
  cset-workflow/app/install_local_cset/bin/install-local-cset.py
Labels: bug, portability

#760 Add missing brackets to TemporaryDirectory call when installing local CSET
  cset-workflow/app/install_local_cset/bin/install-local-cset.py
Labels: bug, small
