Repository MetOffice/CSET, pull requests merged in 2024-05, with the labels that each got.

#587 Colourbar global passthrough
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  cset-workflow/flow.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  docs/source/reference/cli.rst
  src/CSET/__init__.py
  src/CSET/operators/__init__.py
  src/CSET/operators/plot.py
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
Labels: enhancement

#543 Add setuptools as dependency of the workflow
  cset-workflow/requirements/environment.yml
  docs/source/changelog.rst
Labels: enhancement, dependencies

#448 Drop python 3.9 support
  .github/workflows/conda-lock.yml
  .github/workflows/pull_request_checks.yml
  cset-workflow/requirements/locks/py39-lock-linux-64.txt
  docs/source/changelog.rst
  pyproject.toml
  requirements/locks/py39-lock-linux-64.txt
  src/CSET/operators/plot.py
Labels: cleanup

#595 Update documentation copyright year
  docs/source/conf.py
Labels: documentation, small

#597 Link missed names in changelog
  docs/source/changelog.rst
Labels: documentation, small

#522 Add functionality to filter by region
  cset-workflow/includes/lfric_deterministic_domain_mean_surface_time_series.cylc
  cset-workflow/includes/lfric_plot_spatial_surface_model_field.cylc
  cset-workflow/meta/rose-meta.conf
  docs/source/changelog.rst
  src/CSET/operators/constraints.py
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  tests/operators/test_constraints.py
Labels: enhancement

#601 Remove unneeded title from PR template
  .github/pull_request_template.md
Labels: small, cleanup

#603 Improve "Add a new diagnostic" documentation
  docs/source/changelog.rst
  docs/source/contributing/getting-started.rst
  docs/source/contributing/git.rst
  docs/source/usage/add-diagnostic.rst
  src/CSET/operators/__init__.py
Labels: documentation

#518 Warn when input files don't exist
  docs/source/changelog.rst
  src/CSET/operators/convection.py
  src/CSET/operators/read.py
  src/CSET/recipes/__init__.py
  tests/operators/test_read.py
  tests/test_recipes.py
Labels: enhancement

#598 Add list of useful git commands
  docs/source/changelog.rst
  docs/source/contributing/git.rst
Labels: documentation

#609 Add some more classifiers to the package metadata
  pyproject.toml
Labels: small

#610 Fix a changelog descrepancy that arose during conflict resolution
  docs/source/changelog.rst
Labels: documentation, small

#620 Create common operators script
  docs/source/changelog.rst
  src/CSET/operators/_utils.py
  tests/operators/test_utils.py
Labels: enhancement, cleanup

#625 Link to discussion forum
  README.md
  docs/source/changelog.rst
  docs/source/index.rst
Labels: documentation, small

#624 Add GenAI Policy
  .github/pull_request_template.md
  docs/source/changelog.rst
  docs/source/contributing/index.rst
Labels: documentation

#602 Note that structured LFRic is needed rather than UMified
  cset-workflow/meta/rose-meta.conf
Labels: documentation, small

#606 Install restricted files improvements
  cset-workflow/install_restricted_files.sh
  docs/source/changelog.rst
  docs/source/usage/workflow-installation.rst
Labels: enhancement

#627 Normalise LFRic cubes during load
  docs/source/changelog.rst
  src/CSET/operators/read.py
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  tests/operators/test_read.py
Labels: enhancement

#615 Clarify linking the recipe into the rest of CSET
  docs/source/usage/add-diagnostic.rst
Labels: documentation, small

#643 Tweak GenAI attribution PR check wording
  .github/pull_request_template.md
Labels: documentation, small

#353 Adds inflow layer properties diagnostic
  cset-workflow/includes/deterministic_plot_inflow_properties.cylc
  cset-workflow/meta/rose-meta.conf
  src/CSET/operators/convection.py
  src/CSET/recipes/inflow_layer_properties_plot.yaml
  tests/operators/test_convection.py
  tests/test_data/convection/BLheight.nc
  tests/test_data/convection/ECFlagB_2.nc
  tests/test_data/convection/ECFlagD.nc
  tests/test_data/convection/EIB.nc
  tests/test_data/convection/Orography.nc
Labels: enhancement, science

#647 Include cartopy downloaded resources in GitHub Actions cache
  .github/workflows/documentation.yml
  .github/workflows/pull_request_checks.yml
  docs/source/changelog.rst
Labels: small, cleanup, github_actions

#645 Group installation logs in testing workflow
  .github/workflows/pull_request_checks.yml
  docs/source/changelog.rst
Labels: small, cleanup

#660 Log whether operator first arg comes from previous step or recipe
  src/CSET/operators/__init__.py
Labels: small

#629 Add gridstat
  cset-workflow/app/metplus_grid_stat/file/GridStat.conf
  cset-workflow/app/metplus_grid_stat/opt/rose-app-niwa.conf
  cset-workflow/app/metplus_grid_stat/rose-app.conf
  cset-workflow/flow.cylc
  cset-workflow/includes/metplus_grid_stat.cylc
  cset-workflow/includes/point_stat.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  docs/source/changelog.rst
Labels: enhancement

#662 661 inflow properties recipe fix
  docs/source/changelog.rst
  src/CSET/recipes/inflow_layer_properties_plot.yaml
Labels: bug, small

#656 Intelligent determination of plotting country lines
  docs/source/changelog.rst
  src/CSET/operators/plot.py
Labels: enhancement, small

#664 Fix docstring typo in xycoord identifier in _utils
  src/CSET/operators/_utils.py
  src/CSET/operators/plot.py
  src/CSET/operators/regrid.py
  tests/operators/test_utils.py
Labels: bug, documentation, small

#604 Replace `locale.getencoding()` with `sys.stdout.encoding`
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  docs/source/changelog.rst
Labels: small, cleanup, portability

#648 Remove unreachable code
  src/CSET/_common.py
Labels: small, cleanup
