Repository MetOffice/CSET, pull requests merged in 2024-11, with the labels that each got.

#869 Correct execute_recipe docstring; it takes an input directory
  src/CSET/operators/__init__.py
Labels: bug, documentation, small

#870 Fix colorbar min and max not being set on pcolormesh plots
  src/CSET/operators/plot.py
Labels: bug, small

#842 Error fetch_fcst task when no data found for a model, as it usually indicates a typo in the data path
  src/CSET/_workflow_utils/fetch_data.py
  tests/workflow_utils/test_fetch_data.py
Labels: bug, small

#871 Rewrite colorbar loading to use default colorbar definition from inside CSET package
  cset-workflow/meta/rose-meta.conf
  scripts/sort_json.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/operators/_colorbar_definition.json
  src/CSET/operators/plot.py
Labels: bug, enhancement

#878 Fix spelling of stratiform_rainfall_rate in colorbar definition
  src/CSET/operators/_colorbar_definition.json
Labels: bug, small

#829 Improve transect title
  src/CSET/operators/plot.py
  src/CSET/operators/transect.py
  tests/test_data/transect_out_umml.nc
  tests/test_data/transect_out_umpl.nc
Labels: enhancement

#892 Update colorbar definitions
  src/CSET/operators/_colorbar_definition.json
Labels: enhancement, small

#906 Fix typo in comment
  src/CSET/_workflow_utils/fetch_data.py
Labels: cleanup

#886 Explicitly use conda-forge conda channel for updating conda and resolving lock files
  .github/workflows/conda-lock.yml
  cset-workflow/requirements/environment.yml
  cset-workflow/requirements/locks/py310-lock-linux-64.txt
  cset-workflow/requirements/locks/py311-lock-linux-64.txt
  cset-workflow/requirements/locks/py312-lock-linux-64.txt
  cset-workflow/requirements/locks/py313-lock-linux-64.txt
  requirements/environment.yml
  requirements/locks/py310-lock-linux-64.txt
  requirements/locks/py311-lock-linux-64.txt
  requirements/locks/py312-lock-linux-64.txt
  requirements/locks/py313-lock-linux-64.txt
Labels: small, cleanup, github_actions

#880 Exclude __main__.py from test coverage measurement
  pyproject.toml
Labels: small, cleanup

#882 Remove HTTP status check as urlopen already does it
  src/CSET/_workflow_utils/fetch_data.py
Labels: small, cleanup

#881 Test templating variables into recipe parser
  src/CSET/_common.py
  tests/test_common.py
Labels: small, cleanup

#883 Test recipe listing and detailing functions
  tests/test_recipes.py
Labels: cleanup

#896 Changes to fix longitude convention to be in the range -180 degrees to 180 degrees where possible
  src/CSET/operators/read.py
  src/CSET/operators/regrid.py
  tests/operators/test_regrid.py
Labels: bug

#904 Disable strict checking that TLS certificates are well formed
  src/CSET/_workflow_utils/fetch_data.py
Labels: bug, small, portability
