Repository MetOffice/CSET, pull requests merged in 2024-06, with the labels that each got.

#683 Parse recipe variables as python literals
  .pre-commit-config.yaml
  cset-workflow/requirements/locks/py310-lock-linux-64.txt
  cset-workflow/requirements/locks/py311-lock-linux-64.txt
  cset-workflow/requirements/locks/py312-lock-linux-64.txt
  requirements/locks/py310-lock-linux-64.txt
  requirements/locks/py311-lock-linux-64.txt
  requirements/locks/py312-lock-linux-64.txt
  src/CSET/_common.py
Labels: enhancement, small

#686 Add v24.6.0 release notes
  docs/source/changelog.rst
Labels: documentation, small

#693 Fixed metplus config issue
  cset-workflow/flow.cylc
  docs/source/changelog.rst
Labels: bug

#663 Clarify error message on missing files
  docs/source/changelog.rst
  src/CSET/operators/read.py
Labels: documentation, small

#700 Correct rst syntax added in #696
  docs/source/contributing/testing.rst
Labels: bug, documentation, small

#701 Suggest descriptive PR titles instead of changelog entry
  .github/pull_request_template.md
  docs/source/changelog.rst
  docs/source/contributing/index.rst
  docs/source/contributing/releases.rst
Labels: documentation, cleanup

#707 Improve PR title documentation in developer's guide
  docs/source/contributing/index.rst
Labels: documentation

#702 Minor wording tweak in marking PR as ready to review docs
  docs/source/contributing/index.rst
Labels: documentation, small

#650 Add canonical URL links to documentation
  docs/source/conf.py
Labels: documentation, small, cleanup

#703 Clarify running specific tests
  docs/source/contributing/testing.rst
Labels: documentation, small
