Repository MetOffice/CSET, pull requests merged in 2024-08, with the labels that each got.

#764 Move all website files under the workflow shared directory
  cset-workflow/app/housekeeping/bin/housekeep.sh
  cset-workflow/app/install_website_skeleton/bin/install-website.sh
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  cset-workflow/flow.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
Labels: enhancement

#766 Fix overwriting when using transect on multiple variables
  cset-workflow/includes/transect.cylc
  src/CSET/recipes/transect.yaml
Labels: bug

#642 Add Q-Q plot functionality
  cset-workflow/Jinja2Globals/zip.py
  cset-workflow/includes/basic_qq_plot.cylc
  cset-workflow/includes/lfric_basic_qq_plot.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/plot.py
  src/CSET/recipes/generic_basic_qq_plot.yaml
  src/CSET/recipes/lfric_generic_basic_qq_plot.yaml
  tests/operators/test_plots.py
Labels: enhancement, science, full_review

#767 Add nc-time-axis to dependencies
  cset-workflow/requirements/locks/py310-lock-linux-64.txt
  cset-workflow/requirements/locks/py311-lock-linux-64.txt
  cset-workflow/requirements/locks/py312-lock-linux-64.txt
  pyproject.toml
  requirements/environment.yml
  requirements/locks/py310-lock-linux-64.txt
  requirements/locks/py311-lock-linux-64.txt
  requirements/locks/py312-lock-linux-64.txt
Labels: dependencies

#772 Fix plot frames jumping around
  cset-workflow/flow.cylc
  src/CSET/operators/plot.py
Labels: bug

#781 Preload plot images on web page
  src/CSET/operators/_plot_page_template.html
Labels: enhancement

#577 Extract single point data
  cset-workflow/includes/deterministic_single_point_surface_time_series.cylc
  cset-workflow/meta/rose-meta.conf
  docs/source/changelog.rst
  src/CSET/operators/regrid.py
  src/CSET/recipes/generic_surface_single_point_time_series.yaml
  tests/operators/test_regrid.py
Labels: enhancement

#796 Filter irrelevant warning raised by regrid test
  tests/operators/test_regrid.py
Labels: small, cleanup

#790 Merge and concatinate cubes on load
  src/CSET/operators/read.py
  tests/operators/test_read.py
  tests/test_data/concat_after_fix_1.nc
  tests/test_data/concat_after_fix_2.nc
Labels: bug

#778 Allow Point cell methods for empty constraint, making it possible to unify UM and LFRic recipes
  src/CSET/operators/constraints.py
  tests/operators/test_constraints.py
Labels: enhancement

#791 Merge install_local_cset into build_conda so environment is setup in a single cylc task
  cset-workflow/app/build_conda/bin/build_conda_env.sh
  cset-workflow/app/build_conda/bin/install-local-cset.sh
  cset-workflow/app/install_local_cset/bin/install-local-cset.py
  cset-workflow/app/install_local_cset/rose-app.conf
  cset-workflow/flow.cylc
Labels: cleanup

#789 Convert time AuxCoord to DimCoord for LFRic data
  src/CSET/operators/read.py
  tests/operators/test_read.py
Labels: bug

#793 Cancel running PR checks if new commit is pushed
  .github/workflows/pull_request_checks.yml
Labels: small, cleanup, github_actions

#800 Stop ruff warning about ignore-init-module-imports
  pyproject.toml
Labels: small, cleanup

#802 Parsing of float in workflow
  cset-workflow/includes/lfric_plot_spatial_mlevel_model_field.cylc
  cset-workflow/includes/plot_spatial_mlevel_model_field.cylc
Labels: bug

#801 General small plot improvements and website organisation
  cset-workflow/extra-meta/alphabetical_dict.py
  cset-workflow/extra-meta/colorbar_dict_alphabetical.json
  cset-workflow/extra-meta/sort_json.py
  src/CSET/operators/plot.py
  src/CSET/recipes/CAPE_ratio_plot.yaml
  src/CSET/recipes/generic_domain_mean_vertical_profile_modellevel_series.yaml
  src/CSET/recipes/generic_domain_mean_vertical_profile_series.yaml
  src/CSET/recipes/generic_histogram_series.yaml
  src/CSET/recipes/generic_mlevel_spatial_plot_sequence.yaml
  src/CSET/recipes/generic_plevel_spatial_plot_sequence.yaml
  src/CSET/recipes/generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/generic_surface_histogram_series.yaml
  src/CSET/recipes/generic_surface_single_point_time_series.yaml
  src/CSET/recipes/generic_surface_spatial_plot_sequence.yaml
  src/CSET/recipes/inflow_layer_properties_plot.yaml
  src/CSET/recipes/lfric_generic_domain_mean_vertical_profile_series.yaml
  src/CSET/recipes/lfric_generic_histogram_series.yaml
  src/CSET/recipes/lfric_generic_mlevel_spatial_plot_sequence.yaml
  src/CSET/recipes/lfric_generic_plevel_spatial_plot_sequence.yaml
  src/CSET/recipes/lfric_generic_surface_domain_mean_time_series.yaml
  src/CSET/recipes/lfric_generic_surface_spatial_plot_sequence.yaml
  src/CSET/recipes/stash_surface_domain_mean_time_series.yaml
  src/CSET/recipes/stash_surface_spatial_plot_sequence.yaml
Labels: enhancement

#792 Move workflow utility code into unstable module within CSET package
  cset-workflow/app/fetch_fcst/bin/fetch-data-filesystem.py
  cset-workflow/app/finish_website/bin/finish-website.py
  cset-workflow/app/run_cset_recipe/bin/run-cset-recipe.py
  cset-workflow/app/send_email/bin/send-email.py
  src/CSET/_workflow_utils/__init__.py
  src/CSET/_workflow_utils/fetch_data_filesystem.py
  src/CSET/_workflow_utils/finish_website.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/_workflow_utils/send_email.py
  src/CSET/_workflow_utils/validity_time_tester.py
  tests/workflow_utils/test_fetch_data.py
  tests/workflow_utils/test_finish_website.py
  tests/workflow_utils/test_run_cset_recipe.py
  tests/workflow_utils/test_send_email.py
Labels: cleanup

#787 Add pcolormesh plotting operator
  src/CSET/operators/plot.py
  tests/operators/test_plots.py
  tests/operators/test_transect.py
Labels: enhancement

#788 Use pcolormesh for Quicklook surface spatial plots
  src/CSET/recipes/generic_surface_spatial_plot_sequence.yaml
Labels: enhancement, small

#794 Create the plot index in finish_website to avoid a data race between concurrent index writers
  src/CSET/_common.py
  src/CSET/_workflow_utils/finish_website.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  tests/test_common.py
  tests/workflow_utils/test_finish_website.py
  tests/workflow_utils/test_run_cset_recipe.py
Labels: bug

#814 Documentation for data time cycling
  docs/source/changelog.rst
  docs/source/contributing/code-review.rst
  docs/source/contributing/documentation.rst
  docs/source/getting-started/create-first-recipe.rst
  docs/source/getting-started/recipe-graph-details.svg
  docs/source/getting-started/recipe-graph.svg
  docs/source/getting-started/run-recipe.rst
  docs/source/getting-started/visualise-recipe.rst
  docs/source/reference/cli.rst
  docs/source/reference/recipe-format.rst
  docs/source/usage/add-diagnostic.rst
  docs/source/usage/workflow-installation.rst
  src/CSET/operators/plot.py
Labels: documentation
