Repository MetOffice/CSET, pull requests merged in 2025-04, with the labels that each got.

#1277 Add option to skip writing output
  cset-workflow/flow.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/meta/rose-meta.conf.jinja2
  src/CSET/__init__.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/operators/__init__.py
  src/CSET/operators/write.py
  tests/operators/test_write.py
  tests/test_execute_recipe.py
Labels: enhancement

#1311 Avoid writing meta.json outside tempdir during test
  tests/operators/test_write.py
Labels: small, cleanup

#1313 Retry failed processing tasks
  cset-workflow/flow.cylc
Labels: bug

#1320 Add SKIP_WRITE to example configuration
  cset-workflow/opt/rose-suite-RAL3LFRIC.conf
  cset-workflow/rose-suite.conf.example
Labels: bug, small

#1316 Drop support for python 3.10
  .github/workflows/conda-lock.yml
  .github/workflows/pull-request-checks.yml
  .pre-commit-config.yaml
  cset-workflow/requirements/workflow-locks/py310-lock-linux-64.txt
  pyproject.toml
  requirements/locks/py310-lock-linux-64.txt
  src/CSET/__init__.py
  src/CSET/_workflow_utils/fetch_data.py
Labels: cleanup

#1301 Add preprocessing task to speed up workflow
  cset-workflow/app/preprocess_data/bin/preprocess.py
  cset-workflow/app/preprocess_data/rose-app.conf
  cset-workflow/flow.cylc
  src/CSET/_workflow_utils/preprocess.py
  tests/workflow_utils/test_preprocess.py
Labels: enhancement

#1270 Add model level support to CSET
  cset-workflow/includes/plot_spatial_mlevel_model_field.cylc
  cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_hour_of_day.cylc
  cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_lead_time.cylc
  cset-workflow/includes/plot_spatial_mlevel_model_field_case_study_aggregation_validity_time.cylc
  cset-workflow/includes/spatial_mlevel_difference.cylc
  cset-workflow/includes/spatial_mlevel_difference_case_study_aggregation_hour_of_day.cylc
  cset-workflow/includes/spatial_mlevel_difference_case_study_aggregation_lead_time.cylc
  cset-workflow/includes/spatial_mlevel_difference_case_study_aggregation_validity_time.cylc
  cset-workflow/meta/diagnostics/rose-meta.conf
  cset-workflow/opt/rose-suite-RAL3LFRIC.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/misc.py
  src/CSET/recipes/generic_mlevel_domain_vertical_profile_series_case_aggregation_hour_of_day.yaml
  src/CSET/recipes/mlevel_spatial_difference.yaml
  src/CSET/recipes/mlevel_spatial_difference_case_aggregation_mean_hour_of_day.yaml
  src/CSET/recipes/mlevel_spatial_difference_case_aggregation_mean_lead_time.yaml
  src/CSET/recipes/mlevel_spatial_difference_case_aggregation_mean_validity_time.yaml
Labels: enhancement

#1321 Refactor lfric_time_callback
  src/CSET/operators/read.py
  tests/operators/test_read.py
Labels: cleanup

#1326 Move diagnostic archive creation into bake
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/operators/__init__.py
  tests/test_execute_recipe.py
  tests/workflow_utils/test_run_cset_recipe.py
Labels: cleanup

#1341 Correctly format print-based logging in run_cset_recipe.py
  src/CSET/_workflow_utils/run_cset_recipe.py
Labels: bug, small

#1345 Revert "[CI] Update conda lock files"
  cset-workflow/requirements/workflow-locks/py311-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py312-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py313-lock-linux-64.txt
  requirements/locks/py311-lock-linux-64.txt
  requirements/locks/py312-lock-linux-64.txt
  requirements/locks/py313-lock-linux-64.txt
Labels: bug

#1348 Add category to transect recipe
  src/CSET/recipes/transect.yaml
Labels: bug
