Repository MetOffice/CSET, pull requests merged in 2025-08, with the labels that each got.

#1547 Use python 3.13 when creating developer conda environment
  Makefile
Labels: small, cleanup

#1589 Rename derived section to derived diagnostics for clarity
  docs/source/getting-started/cset_uiA.png
  docs/source/getting-started/cset_uiB.png
  docs/source/getting-started/cset_uiC.png
  docs/source/getting-started/cset_uiD.png
  docs/source/getting-started/cset_uiE.png
  docs/source/getting-started/cset_uiF.png
  docs/source/getting-started/rose-edit.png
  src/CSET/cset_workflow/meta/diagnostics/rose-meta.conf
Labels: bug, small

#1533 Fixes ensemble plotting of profiles
  src/CSET/operators/plot.py
  src/CSET/recipes/generic_level_domain_mean_vertical_profile_series.yaml
  src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_all.yaml
  src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_hour_of_day.yaml
  src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_lead_time.yaml
  src/CSET/recipes/generic_level_domain_mean_vertical_profile_series_case_aggregation_validity_time.yaml
  tests/operators/test_plots.py
Labels: bug

#1598 Add return type for `tmp_working_dir` fixture
  tests/conftest.py
Labels: small, cleanup

#1594 Exclude script entry points from coverage
  src/CSET/cset_workflow/app/finish_website/bin/finish_website.py
  src/CSET/cset_workflow/app/send_email/bin/send_email.py
Labels: small, cleanup

#1595 Add sstrip utility function
  src/CSET/_common.py
  tests/test_common.py
Labels: enhancement, small

#1614 Log rather than warn for existing unpacked recipes
  src/CSET/recipes/__init__.py
  tests/test_recipes.py
Labels: enhancement

#1600 Parse recipe separately from executing it
  src/CSET/__init__.py
  src/CSET/_common.py
  src/CSET/operators/__init__.py
  tests/test_cli.py
  tests/test_common.py
  tests/test_execute_recipe.py
Labels: cleanup

#1602 Add `b64json` jinja utility function
  src/CSET/cset_workflow/app/assign_model_colours/bin/assign_model_colours.py
  src/CSET/cset_workflow/flow.cylc
  src/CSET/cset_workflow/lib/python/jinja_utils.py
  tests/workflow_utils/test_jinja_utils.py
Labels: enhancement

#1584 Add presence of rain diagnostics
  src/CSET/cset_workflow/includes/spatial_difference_field.cylc
  src/CSET/cset_workflow/includes/spatial_field.cylc
  src/CSET/cset_workflow/includes/timeseries_field.cylc
  src/CSET/cset_workflow/meta/diagnostics/rose-meta.conf
  src/CSET/cset_workflow/rose-suite.conf.example
  src/CSET/operators/filters.py
  src/CSET/operators/plot.py
  src/CSET/recipes/rain_presence_domain_mean_time_series.yaml
  src/CSET/recipes/rain_presence_spatial_difference.yaml
  src/CSET/recipes/rain_presence_spatial_plot.yaml
  tests/operators/test_plot.py
Labels: enhancement

#1625 Update spatial_field includes file for correct call to RAIN_PRESENCE_SPATIAL_PLOT
  src/CSET/cset_workflow/includes/spatial_field.cylc
Labels: bug, small

#1623 Update cell_methods constraint to handle maximum and minimum cell methods
  src/CSET/operators/constraints.py
  tests/operators/test_filters.py
Labels: bug, small
