Repository MetOffice/CSET, pull requests merged in 2025-06, with the labels that each got.

#1420 Set 20 minute runtime limit for GitHub Actions jobs
  .github/workflows/conda-lock.yml
  .github/workflows/pre-commit-update.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/release.yml
  .github/workflows/weekly-checks.yml
Labels: enhancement, small, github_actions

#1409 Add subarea configuration to example rose-suite.conf
  cset-workflow/opt/rose-suite-RAL3LFRIC.conf
  cset-workflow/rose-suite.conf.example
Labels: small, cleanup

#1425 Simplify and test conversion from --input-dir to --INPUT_PATHS
  src/CSET/__init__.py
  tests/test_cli.py
Labels: small, cleanup

#1426 More robustly test command line argument parser
  tests/test_cli.py
Labels: cleanup

#1421 Remove environment section from bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: small, cleanup

#1443 Use correct recipe file for surface histogram case aggregation
  src/CSET/recipes/generic_surface_histogram_series_case_aggregation_all.yaml
Labels: bug, small

#1412 Exclude additional VCS files from sdist manifest to prevent them being included in published packages
  MANIFEST.in
Labels: small, cleanup

#1450 Align time units and fix diurnal cycle aggregation bug
  src/CSET/operators/aggregate.py
  src/CSET/operators/collapse.py
  src/CSET/operators/read.py
  tests/operators/test_collapse.py
  tests/operators/test_read.py
Labels: bug

#1462 Rename rose-suite.conf.txt to rose-suite.conf
  src/CSET/workflow/files/app/install_website_skeleton/file/html/placeholder.html
  src/CSET/workflow/finish_website.py
  tests/workflow/test_finish_website.py
Labels: small, cleanup

#1461 Move `make setup` documentation to make it more prominent
  docs/source/contributing/getting-started.rst
Labels: documentation, small

#1460 Remove conda-environment link from development workflow to fix failing tests
  Makefile
  docs/source/contributing/getting-started.rst
  src/CSET/workflow/files/bin/app_env_wrapper
Labels: bug, small

#1471 Include discrete colourbar for spatial visibility_in_air plots
  src/CSET/operators/plot.py
  tests/operators/test_plots.py
Labels: enhancement

#1475 Use temporary working directory for plotting tests
  tests/conftest.py
  tests/operators/test_plots.py
Labels: cleanup
