Repository MetOffice/CSET, pull requests merged in 2025-05, with the labels that each got.

#1352 Symbolic link to raw filesystem data to avoid slow copy
  src/CSET/_workflow_utils/fetch_data.py
  tests/workflow_utils/test_fetch_data.py
Labels: enhancement

#1354 Add additional STASH to LFRic mappings
  src/CSET/operators/_stash_to_lfric.py
Labels: enhancement, small

#1324 Plot all models on a single histogram plot
  cset-workflow/app/assign_model_colours/bin/assign_model_colours.py
  cset-workflow/app/assign_model_colours/rose-app.conf
  cset-workflow/flow.cylc
  cset-workflow/includes/histogram_plevel_field.cylc
  cset-workflow/includes/histogram_plevel_field_aggregation.cylc
  cset-workflow/includes/histogram_plevel_field_aggregation_all.cylc
  cset-workflow/includes/histogram_surface_field.cylc
  cset-workflow/includes/histogram_surface_field_aggregation.cylc
  cset-workflow/includes/histogram_surface_field_aggregation_all.cylc
  cset-workflow/lib/python/jinja_utils.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/operators/plot.py
  src/CSET/operators/read.py
  src/CSET/recipes/generic_plevel_histogram_series.yaml
  src/CSET/recipes/generic_plevel_histogram_series_case_aggregation.yaml
  src/CSET/recipes/generic_plevel_histogram_series_case_aggregation_lead_time.yaml
  src/CSET/recipes/generic_surface_histogram_series.yaml
  src/CSET/recipes/generic_surface_histogram_series_case_aggregation.yaml
  src/CSET/recipes/generic_surface_histogram_series_case_aggregation_lead_time.yaml
  tests/operators/test_read.py
Labels: enhancement

#1357 Add v25.5.0 release notes and document more of the release process
  docs/source/changelog.rst
  docs/source/contributing/releases.rst
Labels: documentation

#1364 Correct model level sort key in rose edit
  cset-workflow/meta/diagnostics/rose-meta.conf
Labels: small

#1260 Support equalising hour coordinate in difference operator
  src/CSET/operators/aggregate.py
  src/CSET/operators/misc.py
  tests/operators/test_misc.py
Labels: enhancement

#1366 Pair cube with corresponding coordinate when plotting line series
  src/CSET/operators/plot.py
  tests/operators/test_plots.py
Labels: bug

#1369 Bump minimum iris version to avoid dask issues
  requirements/environment.yml
Labels: dependencies

#1379 Fix formatting of cset bake example documentation
  docs/source/reference/cli.rst
Labels: documentation, small

#1374 Improve testing of get_cube_coordindex
  src/CSET/operators/_utils.py
  tests/operators/test_utils.py
Labels: small, cleanup

#1382 Add CSET v25.5.1 release notes to changelog
  docs/source/changelog.rst
Labels: documentation

#1387 Various minor GitHub Actions improvements
  .github/workflows/conda-lock.yml
  .github/workflows/pre-commit-update.yml
  .github/workflows/pull-request-checks.yml
  .github/workflows/release.yml
  .github/workflows/weekly-checks.yml
  docs/source/contributing/getting-started.rst
  docs/source/contributing/testing.rst
Labels: cleanup, github_actions

#1390 Add CSET v25.5.2 release notes to changelog
  docs/source/changelog.rst
Labels: documentation, small

#1394 General improvements to plots
  src/CSET/operators/__init__.py
  src/CSET/operators/plot.py
  tests/test_execute_recipe.py
Labels: enhancement
