Repository MetOffice/CSET, pull requests merged in 2025-07, with the labels that each got.

#1487 Clarify adding a recipe to the CSET workflow
  docs/source/usage/add-diagnostic.rst
Labels: documentation, small

#1506 Increases memory for ensemble plotting
  src/CSET/cset_workflow/flow.cylc
Labels: bug

#1499 Update ceilometer_cloud_amount_maxrnd
  src/CSET/cset_workflow/opt/rose-suite-RAL3LFRIC.conf
  src/CSET/operators/_stash_to_lfric.py
Labels: enhancement, small

#1507 Allow ensembles to run for more than ten variables
  src/CSET/cset_workflow/flow.cylc
Labels: bug

#1488 Update the pre-commit hook ID for ruff-check
  .pre-commit-config.yaml
Labels: small, cleanup

#1514 Remove preprocess task
  src/CSET/cset_workflow/app/preprocess_data/bin/preprocess.py
  src/CSET/cset_workflow/app/preprocess_data/rose-app.conf
  src/CSET/cset_workflow/flow.cylc
  src/CSET/operators/read.py
  tests/workflow_utils/test_preprocess.py
Labels: cleanup

#1518 Correct workflow path in documentation
  .gitattributes
  docs/source/usage/add-diagnostic.rst
  docs/source/usage/add-site.rst
Labels: documentation, small

#1523 Reduce required code coverage
  .github/workflows/pull-request-checks.yml
Labels: small, cleanup

#1545 Uppercase "Difference" in plot title
  src/CSET/recipes/surface_spatial_difference_case_aggregation_mean_lead_time.yaml
Labels: small, cleanup
