Repository MetOffice/CSET, pull requests merged in 2025-02, with the labels that each got.

#1100 Handle CubeLists in `plot_vertical_line_series` and `plot_scatter_plot`
  src/CSET/operators/plot.py
Labels: enhancement

#1119 Add dummy tasks to prevent workflow graph failures
  cset-workflow/flow.cylc
Labels: bug, small

#1123 Fix issue where pressure coordinate returns Unit object, not str
  src/CSET/operators/read.py
Labels: bug, small

#1134 switch off auto-scale for x axis to avoid jumping of ticks on x axis …
  src/CSET/operators/plot.py
Labels: small

#1132 Switch web viewer to sidebar layout
  cset-workflow/app/install_website_skeleton/file/html/double.html
  cset-workflow/app/install_website_skeleton/file/html/index.html
  cset-workflow/app/install_website_skeleton/file/html/placeholder.html
  cset-workflow/app/install_website_skeleton/file/html/single.html
  cset-workflow/app/install_website_skeleton/file/html/static/script.js
  cset-workflow/app/install_website_skeleton/file/html/static/style.css
Labels: enhancement

#1137 Histogram enhancements
  cset-workflow/meta/diagnostics/rose-meta.conf
  src/CSET/operators/plot.py
  src/CSET/recipes/generic_plevel_histogram_series.yaml
  src/CSET/recipes/generic_surface_histogram_series.yaml
Labels: enhancement

#1122 Various QuickLook fixes and enhancements of surface plot functionality.
  src/CSET/operators/_stash_to_lfric.py
  src/CSET/operators/misc.py
  src/CSET/operators/read.py
  src/CSET/operators/regrid.py
  tests/operators/test_misc.py
Labels: enhancement

#1141 Search for all varnames and allow user colorbar override
  src/CSET/operators/plot.py
  tests/operators/test_plots.py
Labels: bug

#1151 Unify .gitignore to cover both workflow and library
  .gitignore
  cset-workflow/.gitignore
Labels: small, cleanup

#1153 Update environments used throughout CSET to python 3.13
  .github/workflows/documentation.yml
  .github/workflows/pull_request_checks.yml
  .github/workflows/weekly-checks.yml
  cset-workflow/app/build_conda/bin/build_conda_env.sh
  docs/source/contributing/getting-started.rst
Labels: small, cleanup

#1157 Rename workflow conda lock files
  .github/workflows/conda-lock.yml
  cset-workflow/app/build_conda/bin/build_conda_env.sh
  cset-workflow/requirements/workflow-environment.yaml
  cset-workflow/requirements/workflow-locks/py310-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py311-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py312-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py313-lock-linux-64.txt
Labels: small, cleanup

#1156 Always build conda environment within workflow share directory
  cset-workflow/app/build_conda/bin/build_conda_env.sh
  cset-workflow/app/build_conda/bin/install-local-cset.sh
  cset-workflow/bin/app_env_wrapper
  cset-workflow/flow.cylc
  cset-workflow/meta/rose-meta.conf
  cset-workflow/meta/rose-meta.conf.jinja2
  cset-workflow/rose-suite.conf.example
Labels: enhancement

#1160 Break long names in sidebar
  cset-workflow/app/install_website_skeleton/file/html/static/style.css
Labels: bug, small

#1161 Allow release workflow to run on pre-releases
  .github/workflows/release.yml
Labels: bug, small

#1159 Unify documentation building Action into pull requests check workflow
  .github/workflows/documentation.yml
  .github/workflows/pull-request-checks.yml
Labels: cleanup

#1158 Small additions to regrid and callback
  cset-workflow/meta/diagnostics/rose-meta.conf
  cset-workflow/rose-suite.conf.example
  src/CSET/operators/misc.py
  src/CSET/operators/read.py
Labels: small

#1168 Revert to python 3.12 for workflow environment
  cset-workflow/app/build_conda/bin/build_conda_env.sh
Labels: bug, small, portability

#1169 Add missing settings to example suite config
  cset-workflow/rose-suite.conf.example
Labels: bug, small

#1177 Remove any repeated or UM colorbars
  src/CSET/operators/_colorbar_definition.json
Labels: bug, small

#1181 Add colorbar ranges for different pressure levels
  src/CSET/operators/_colorbar_definition.json
Labels: enhancement, small

#1184 Add shellcheck to pre-commit hooks
  .pre-commit-config.yaml
  cset-workflow/bin/app_env_wrapper
Labels: cleanup

#1186 Set website display date at plot creation
  src/CSET/_workflow_utils/finish_website.py
  src/CSET/operators/plot.py
  tests/operators/test_plots.py
Labels: bug

#1185 Simplify logging
  src/CSET/__init__.py
  src/CSET/_workflow_utils/run_cset_recipe.py
  src/CSET/operators/__init__.py
  tests/test_cli.py
Labels: enhancement

#1200 Test matplotlib font logs are filtered out
  tests/test_cli.py
Labels: small, cleanup

#1205 Remove unneeded callback
  src/CSET/operators/read.py
Labels: cleanup

#1203 Error build_conda when local CSET path not set
  cset-workflow/app/build_conda/bin/install-local-cset.sh
Labels: bug, small

#1211 Draw attention to the hyperlink to download the example
  docs/source/getting-started/run-recipe.rst
  docs/source/getting-started/visualise-recipe.rst
Labels: documentation, small

#1219 Create needed parent directories when writing the website
  cset-workflow/app/install_website_skeleton/bin/install-website.sh
  cset-workflow/meta/rose-meta.conf
  cset-workflow/meta/rose-meta.conf.jinja2
Labels: enhancement, small
