Repository MetOffice/CSET, pull requests merged in 2025-01, with the labels that each got.

#1022 Log cubes that don't merge in `load_cube` operator
  src/CSET/operators/read.py
Labels: small, cleanup

#1024 Remove unneeded `name` global attribute
  src/CSET/operators/read.py
Labels: bug, small

#1002 Adds DKE functionality
  docs/source/reference/operators.rst
  src/CSET/operators/__init__.py
  src/CSET/operators/ensembles.py
  src/CSET/recipes/example_DKE.yaml
  tests/operators/test_ensembles.py
Labels: enhancement

#1041 Format JSON when writing
  src/CSET/_common.py
  src/CSET/_workflow_utils/finish_website.py
  src/CSET/operators/__init__.py
  src/CSET/operators/plot.py
Labels: small, cleanup

#1039 Require tasks to succeed in DEBUG mode
  cset-workflow/flow.cylc
  cset-workflow/meta/rose-meta.conf
Labels: enhancement, small

#1042 Generalise spatial plot log message
  src/CSET/operators/plot.py
Labels: small, cleanup

#1043 Seperate words in callback function name with _ so it is easier to read
  src/CSET/operators/read.py
  tests/operators/test_read.py
Labels: small, cleanup

#1046 Handle sorting files outside the current directory in `sort_json.py` script
  scripts/sort_json.py
Labels: bug, small

#1047 Replace all remaining usage of typing.Union with `|`
  src/CSET/_common.py
  src/CSET/graph.py
  src/CSET/operators/__init__.py
  src/CSET/operators/collapse.py
  src/CSET/operators/filters.py
  src/CSET/operators/misc.py
  src/CSET/operators/write.py
Labels: small, cleanup

#1051 Fix typo in rose-edit help
  cset-workflow/meta/rose-meta.conf
Labels: documentation, small

#1035 Add configuration file for GitHub Issue templates
  .github/ISSUE_TEMPLATE/config.yml
Labels: small, cleanup

#1052 Add utility function for equalising attributes
  src/CSET/operators/_utils.py
  tests/operators/test_utils.py
Labels: enhancement

#1045 Reduce useless log messages
  src/CSET/__init__.py
  src/CSET/operators/read.py
Labels: cleanup

#1034 Adds collapse_by_hour_of_day operator
  src/CSET/operators/collapse.py
  tests/operators/test_collapse.py
  tests/test_data/long_forecast_air_temp_fcst_1.nc
Labels: enhancement

#1060 Sort colorbar JSON files via pre-commit hook
  .pre-commit-config.yaml
  scripts/sort_json.py
Labels: cleanup

#1067 Collapse by validity time
  src/CSET/operators/collapse.py
  tests/operators/test_collapse.py
Labels: enhancement

#1068 Update collapse_by_hour for multiple cases
  src/CSET/operators/_utils.py
  src/CSET/operators/collapse.py
  tests/operators/test_collapse.py
  tests/operators/test_utils.py
  tests/test_data/medium_forecast_air_temp_monotonic.nc
Labels: enhancement

#1074 Accept microsecond precision in iris times
  src/CSET/operators/__init__.py
Labels: small, cleanup

#1075 Use "spawn" start method for multiprocessing
  src/CSET/operators/ageofair.py
Labels: small, cleanup

#1082 Fix issue with rose-suite.conf variable
  cset-workflow/rose-suite.conf.example
Labels: bug, small

#1081 Remove unnecessary computation from age-of-air test
  tests/operators/test_ageofair.py
Labels: cleanup

#1080 Share multiprocessing pool across ensemble members
  src/CSET/operators/ageofair.py
Labels: enhancement

#1064 Add additional colour bar definitions from UKEP Plot
  src/CSET/operators/_colorbar_definition.json
Labels: enhancement, science

#1090 Increase default memory to 4G for processes
  cset-workflow/flow.cylc
Labels: small

#1091 Deduplicate an unlimited amount of STASH warnings
  src/CSET/operators/read.py
Labels: cleanup

#1089 Search for correct log_record in fetch_data tests
  tests/workflow_utils/test_fetch_data.py
Labels: bug, cleanup

#1095 Implement required return value for MASSFileRetriever
  cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
Labels: bug

#1104 Remove housekeep_raw task from workflow
  cset-workflow/flow.cylc
Labels: bug, enhancement

#985 Allow `collapse.collapse` to handle a CubeList
  src/CSET/operators/collapse.py
  tests/operators/test_collapse.py
Labels: enhancement
