Repository MetOffice/CSET, pull requests merged in 2025-03, with the labels that each got.

#1220 Remove tox
  docs/source/contributing/documentation.rst
  docs/source/contributing/testing.rst
  docs/source/usage/add-diagnostic.rst
  pyproject.toml
  requirements/environment.yml
Labels: cleanup, dependencies

#1223 Updated vertical line series pressure maximum y limit to 100hPa.
  src/CSET/operators/plot.py
Labels: small

#1190 Create standard rose-suite.conf for RAL3-LFRic, with all variables populated.
  cset-workflow/opt/rose-suite-RAL3LFRIC.conf
Labels: documentation

#1227 Model level callback to allow LFRic cubes to merge
  src/CSET/operators/read.py
  tests/operators/test_read.py
  tests/test_data/model_level_test.nc
Labels: bug, small

#1208 Add case date as subcategory for output website
  cset-workflow/app/install_website_skeleton/file/html/static/script.js
  src/CSET/_workflow_utils/finish_website.py
  tests/workflow_utils/test_finish_website.py
Labels: enhancement

#1238 Add changelog entry for v25.3.0
  docs/source/changelog.rst
Labels: documentation

#1218 Getting started documentation improvements
  docs/source/conf.py
  docs/source/getting-started/index.rst
  docs/source/getting-started/installation.rst
  docs/source/getting-started/rose-edit.png
  docs/source/getting-started/run-recipe.rst
  docs/source/getting-started/visualise-recipe.rst
  docs/source/getting-started/workflow-installation.rst
  docs/source/getting-started/workflow-run.rst
  docs/source/index.rst
  docs/source/reference/glossary.rst
  docs/source/usage/index.rst
  docs/source/usage/rose-edit.png
  docs/source/usage/workflow-installation.rst
Labels: documentation

#1248 Check for staggered grid with name rather than STASH in difference operator
  src/CSET/operators/misc.py
  tests/operators/test_misc.py
Labels: bug

#1249 Fully sort website index
  src/CSET/_common.py
  src/CSET/_workflow_utils/finish_website.py
  tests/test_common.py
Labels: enhancement

#1250 Increase aggregation wallclock to 3 hours
  cset-workflow/flow.cylc
Labels: enhancement, small

#1120 Skip running dummy tasks
  cset-workflow/flow.cylc
Labels: enhancement, small

#1251 Document adding a site-specific configuration
  docs/source/usage/add-site.rst
  docs/source/usage/index.rst
Labels: documentation

#1278 Avoid accessing non-captured output in MASS fetch script
  cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
Labels: bug, small

#1286 Add release notes for v25.3.1
  docs/source/changelog.rst
Labels: documentation, small

#1281 Overwrite partially downloaded files from MASS
  cset-workflow/app/fetch_fcst/bin/fetch-data-mass.py
Labels: bug, small

#1291 Update workflow CSET package
  cset-workflow/requirements/workflow-locks/py310-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py311-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py312-lock-linux-64.txt
  cset-workflow/requirements/workflow-locks/py313-lock-linux-64.txt
Labels: small, dependencies

#1292 Ignore codespell error for "runN"
  pyproject.toml
Labels: small

#1213 Add fully worked example with CYLC to documentation
  docs/source/getting-started/cset_ui1.PNG
  docs/source/getting-started/cset_ui2.PNG
  docs/source/getting-started/cset_ui3.png
  docs/source/getting-started/index.rst
  docs/source/getting-started/run_full_cylc_workflow.rst
  pyproject.toml
Labels: documentation

#1268 include precipitation specific colorbar and unit conversion
  src/CSET/operators/_colorbar_definition.json
  src/CSET/operators/plot.py
Labels: enhancement
